/*
 * Copyright 2026 Google LLC
 * SPDX-License-Identifier: Apache-2.0
 */

import assert from "node:assert/strict";
import { execFileSync, spawnSync } from "node:child_process";
import { mkdtempSync, mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import test from "node:test";
import { fileURLToPath } from "node:url";

const main = join(dirname(fileURLToPath(import.meta.url)), "main.ts");

function fixture(makefile: string): { directory: string; cleanup: () => void } {
  const directory = mkdtempSync(join(tmpdir(), "tkati-ninja-options-"));
  writeFileSync(join(directory, "Makefile"), makefile);
  return { directory, cleanup: () => rmSync(directory, { recursive: true, force: true }) };
}

test("ninja directory, suffix, jobs, phony outputs, and validations are honored", () => {
  const { directory, cleanup } = fixture(`
.PHONY: all check
all: .KATI_VALIDATIONS := check
all:
\t@:
check:
\t@:
`);
  try {
    mkdirSync(join(directory, "out"));
    execFileSync(process.execPath, [main, "--ninja", "--regen", "--ninja_dir", "out", "--ninja_suffix=_test",
      "-j2", "--remote_num_jobs=3", "--use_ninja_phony_output", "--use_ninja_validations"], { cwd: directory });

    const ninja = readFileSync(join(directory, "out/build_test.ninja"), "utf8");
    assert.match(ninja, /^builddir = out$/m);
    assert.match(ninja, /^pool local_pool\n  depth = 2$/m);
    assert.doesNotMatch(ninja, /_kati_always_build_/);
    assert.match(ninja, /^build all: rule\d+ \|@ check$/m);
    assert.match(ninja, /^  phony_output = true$/m);
    assert.match(ninja, /^  pool = local_pool$/m);

    const shell = readFileSync(join(directory, "out/ninja_test.sh"), "utf8");
    assert.match(shell, /^\. out\/env_test\.sh$/m);
    assert.match(shell, /^exec ninja -f out\/build_test\.ninja -j3 "\$@"$/m);
    assert.doesNotThrow(() => readFileSync(join(directory, "out/.kati_stamp_test")));

    // A clean --regen invocation must find and reuse the suffixed files in ninja_dir.
    execFileSync(process.execPath, [main, "--ninja", "--regen", "--ninja_dir", "out", "--ninja_suffix=_test",
      "-j2", "--remote_num_jobs=3", "--use_ninja_phony_output", "--use_ninja_validations"], { cwd: directory });
  } finally {
    cleanup();
  }
});

test("empty ninja output and suppressed prelude match their flags", () => {
  const { directory, cleanup } = fixture("all:\n\t@:\n");
  try {
    execFileSync(process.execPath, [main, "--ninja", "--empty_ninja_file", "--no_ninja_prelude"], { cwd: directory });
    assert.equal(readFileSync(join(directory, "build.ninja"), "utf8"), "# Generated by tkati\n");
  } finally {
    cleanup();
  }
});

test("validations require --use_ninja_validations", () => {
  const { directory, cleanup } = fixture("all: .KATI_VALIDATIONS := check\nall:\n\t@:\ncheck:\n\t@:\n");
  try {
    const result = spawnSync(process.execPath, [main, "--ninja"], { cwd: directory, encoding: "utf8" });
    assert.notEqual(result.status, 0);
    assert.match(result.stderr, /\.KATI_VALIDATIONS not allowed without --use_ninja_validations/);
  } finally {
    cleanup();
  }
});
